SUPPORTED_EXTENSIONS = {
    '.jpg', '.jpeg', '.png', '.heic', '.heif', '.webp', '.bmp',
}

MAX_IMAGE_DIMENSION = 640
FACE_CONFIDENCE_THRESHOLD = 0.5
MAX_FACES_PER_IMAGE = 50
FACE_AUTO_MATCH_THRESHOLD = 0.85
FACE_POSSIBLE_MATCH_THRESHOLD = 0.7

BURST_TIME_GAP_SECONDS = 2
BURST_PHASH_DISTANCE = 15
BURST_HERO_COUNT = 1
BURST_BACKUP_COUNT = 1

BLUR_LAPLACIAN_THRESHOLD = 100
BLUR_MODERATE_THRESHOLD = 50
BLUR_BLURRY_THRESHOLD = 20

JUNK_PROBABILITY_THRESHOLD = 0.7
TOP_MEMORY_SCORE_THRESHOLD = 0.85
FAMILY_PRIORITY_THRESHOLD = 7
TRAVEL_HIGHLIGHT_SCORE_THRESHOLD = 0.6

MEMORY_SCORE_W1 = 0.40
MEMORY_SCORE_W2 = 0.30
MEMORY_SCORE_W3 = 0.20
MEMORY_SCORE_W4 = 0.10

BATCH_SIZE = 8
MAX_WORKERS = 4

SCENE_CATEGORIES = [
    "landscape", "indoor", "portrait", "food", "city",
    "nature", "event", "travel", "document", "art_meme",
]

SCENE_WEIGHTS = {
    "landscape": 0.8,
    "travel": 0.9,
    "portrait": 0.7,
    "event": 0.7,
    "nature": 0.6,
    "food": 0.5,
    "indoor": 0.4,
    "city": 0.6,
    "art_meme": 0.3,
    "document": 0.1,
}

FACE_PRIORITY_IMMEDIATE_FAMILY = 10
FACE_PRIORITY_EXTENDED_FAMILY = 7
FACE_PRIORITY_FRIENDS = 5
FACE_PRIORITY_ACQUAINTANCES = 3
FACE_PRIORITY_UNKNOWN = 1

LOW_RESOLUTION_THRESHOLD = 200
WHATSAPP_PATH_PATTERNS = ["whatsapp", "img-20", "wa-"]
